[global]
#template_dir = "static"
[development]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
limits = { forms = 32768, json = 1048576 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
limits = { forms = 32768, json = 1048576 }

[production]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "critical"
limits = { forms = 32768, json = 1048576 }
